site_name: Bluewater Technical Documentation
docs_dir: technical

theme:
  name: material
  palette:
    primary: blue
    accent: light blue
  features:
    - navigation.tabs
    - navigation.instant
    - search.suggest
    - search.highlight

# Add your logo here if desired
# logo: images/logo.png

nav:
  - Home: index.md
  - Getting Started: getting-started.md
  - Configuration Guide: configuration.md
  - Extending & Integration: extending.md
  - Deployment & Operations: deployment.md
  - FAQ & Troubleshooting: faq.md
  - Examples:
      - Example 1: examples/example1.md
      - Example 2: examples/example2.md

markdown_extensions:
  - admonition
  - codehilite
  - toc:
      permalink: true
  - footnotes
  - tables

extra_css:
  - css/custom.css   # (Optional: add if you create /technical/css/custom.css)

# Optional: Set site URL for deployment
# site_url: https://BluewaterMVC.github.io/bluewater-framework/

# Optional: Repository link
repo_url: https://github.com/BluewaterMVC/bluewater-framework
repo_name: Bluewater Framework

# Optional: Edit on GitHub button
edit_uri: edit/main/technical/
