name: Update Changelog

on:
  push:
    tags:
      - 'v*.*.*'
  workflow_dispatch:

jobs:
  build_changelog:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Generate changelog
        uses: mikepenz/release-changelog-builder-action@v4.1.0
        with:
          configuration: |
            changelog:
              owner: ${{ github.repository_owner }}
              repo: ${{ github.event.repository.name }}
              outputFile: CHANGELOG.md
              useIssueTitle: true

      - name: Commit and push changelog
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "github-actions"
          git add CHANGELOG.md
          git commit -m "chore: update CHANGELOG.md [skip ci]" || echo "No changes to commit"
          git push
